/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'category', collapsed: false, label: "General", items: ['intro',{type: 'autogenerated', dirName: 'general'}]},
    {type: 'category', collapsed: false, label: "HTTP API", link: {type: "generated-index", title: "HTTP API", description: 'Please follow the link to access the Wildduck API documentation'}, items: [{type: 'link', label: "Wildduck API", href: "/docs/category/wildduck-api"}, 'api-general/api-error-codes']},
    {type: 'category', collapsed: false, label: "Additional Software", items: [{type: 'autogenerated', dirName: 'additional-software'}]},
    {type: 'category', collapsed: false, label: "In Depth", items: [{type: 'autogenerated', dirName: 'in-depth'}]}
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "Wildduck API",
      link: {
        type: "generated-index",
        title: "Wildduck API",
        description: "This is the API documentation for Wildduck Email Server",
        slug: "/category/wildduck-api"
      },
      items: require("./docs/wildduck-api/sidebar.js")
    }
  ]
};

export default sidebars;